version: 0.1

environment_variables:
  plaintext:
     phase: "alpha"
     
#phases:
#  pre_build:
#    commands:
#     - mvn clean
    
build:
  commands:
    - mvn package
    
artifacts:
  files:
    - '**/*'
  name: $Env:TEST_ENV_VARIABLE-$(Get-Date -UFormat "%Y%m%d-%H%M%S")

  discard-paths: yes
